In [13]:
import pandas as pd
import geopandas as gpd
import glob
import re

In [ ]:
# Combine individual tree canopy geojson file sinto a single file with property for each year

In [8]:
geojson = glob.glob("./*.json")

dfs = []
for file in geojson:   
    year = re.findall('\d+',file)[0] # get year as string from filename

    df = gpd.read_file(file)
    df["frac"] = df["frac"]*100
    df = df.rename(columns={"frac": year})
    # df = df.set_index(['CTUID','geometry','DGUID','PRUID'])
    df = df.set_index(['name','geometry'])
    dfs.append(df)

In [9]:
tree_canopy = pd.concat(dfs,axis=1, join='inner').round(2)

In [10]:
tree_canopy = tree_canopy.reset_index().set_geometry("geometry")

In [12]:
tree_canopy.to_file("Tree_canopy.geojson", driver="GeoJSON")

In [11]:
tree_canopy

,name,geometry,2020,2017,2022,2015,2012,2013
0,12I,"POLYGON ((-113.94716 50.86311, -113.94563 50.8...",4.26,3.28,4.47,3.52,3.69,3.57
1,SETON,"POLYGON ((-113.92931 50.87049, -113.92922 50.8...",1.25,0.84,1.36,0.70,0.65,0.65
2,RANGEVIEW,"POLYGON ((-113.93383 50.88507, -113.93363 50.8...",0.43,0.30,0.34,0.53,0.53,0.53
3,12J,"POLYGON ((-113.85991 50.85775, -113.86006 50.8...",1.33,1.24,1.32,1.14,1.14,1.14
4,AUBURN BAY,"POLYGON ((-113.96582 50.88044, -113.97371 50.8...",3.61,2.74,3.77,2.20,2.06,2.06
...,...,...,...,...,...,...,...,...
297,CARRINGTON,"POLYGON ((-114.08295 51.18334, -114.07130 51.1...",0.48,1.07,0.64,0.87,0.88,0.88
298,GLACIER RIDGE,"POLYGON ((-114.16460 51.19689, -114.16460 51.1...",1.00,1.05,0.72,0.68,0.64,0.64
299,02K,"POLYGON ((-114.18768 51.18335, -114.18772 51.1...",0.58,0.54,0.58,0.49,0.48,0.48
300,AMBLETON,"POLYGON ((-114.11790 51.18315, -114.11790 51.1...",0.01,0.79,0.04,1.07,1.07,1.07
301,02L,"POLYGON ((-114.09459 51.18359, -114.09459 51.1...",1.88,1.97,1.88,1.76,1.69,1.69